server:
  port: 8443  # HTTPS를 8443에서 처리
  ssl:
    enabled: true  # SSL 활성화
    key-store: classpath:/static/config1/keystore.p12  # 키스토어 파일 경로
    key-store-password: 870843  # 키스토어 비밀번호
    key-store-type: PKCS12  # 키스토어 타입
    key-alias: mylocalcert  # 키 알리아스

  servlet:
    context-path: /
    jsp-servlet:
      class-name: org.apache.jasper.servlet.JspServlet
      init-parameters:
        development: "false"  # 개발 모드 비활성화

spring:
  application:
    name: hotel-service  # 애플리케이션 이름

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.2.131:1521/xe
    username: hr
    password: hr

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Hibernate SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리를 포맷팅
        use_sql_comments: true  # SQL 주석 활성화
        generate_statistics: true  # Hibernate 통계 활성화

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 41211a2d42ebba192243003ab70cacc9
            client-secret: PBFDPH3s6hvUPvvPOqhycFo6zYPW3a7n
            redirect-uri: "https://localhost:8443/oauth2/success"  # HTTPS로 리디렉션
            authorization-grant-type: authorization_code
          naver:  # 네이버 로그인 API 설정
            client-id: ZCu6SjlzSG3mKIvbTW1e
            client-secret: i9tNmWN5dX
            redirect-uri: "https://localhost:8443/naver/success"  # HTTPS로 리디렉션
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            user-info-authentication-method: header
          naver:  # 네이버 로그인 API 제공자 설정
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.id

  jwt:
    secret: your secret key
    expiration: 3600000

  mail:
    host: smtp.naver.com
    port: 587
    username: jho8719@naver.com  # 네이버 이메일
    password: 5G3TYJW8JZ34  # 네이버 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com

  mvc:
    view:
      prefix: /WEB-INF/views/  # JSP 파일 경로
      suffix: .jsp             # JSP 파일 확장자

  web:
    cors:
      allowed-origin-patterns: "http://localhost:8084"  # 허용할 출처
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"   # 허용할 HTTP 메서드
      allowed-headers: "Authorization,Content-Type"    # 허용할 헤더
      allow-credentials: true                          # 자격 증명 허용

  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # MyBatis SQL 로그를 표준 출력으로 설정

logging:
  level:
    org:
      spring:
        security: DEBUG       # Spring Security 디버깅 로그 활성화
        web: DEBUG            # Spring Web 관련 디버깅 로그 활성화
    mybatis: DEBUG           # MyBatis 디버깅 로그
    hibernate:
      SQL: DEBUG
    com:
      example: DEBUG         # 애플리케이션 관련 로그 (예: com.example)



